### ISSUE TITLE
o-teaser-collection 

### ISSUE THREAD

**Issue by debugwand** [Financial-Times/o-teaser-collection#16]
Are there any plans to split o-teaser-collections into something more atomic?

I’ve been looking into an issue raised by QA where something in article uses 5 styles from o-teaser-collections and as that is in main, users on wider screens on poor connections get a flash of half-styled content. Testing what happens when I move that into the header, it adds about 10KB to the page.

The styles involved are
* o-teaser-collection
* o-teaser-collection__heading
* o-teaser-collection__heading--small
* o-teaser-collection__items
* o-teaser-collection__item

The bit concerned is the Latest Articles block in the right hand rail in articles if you want to take a look.

**Comment by JakeChampion** [comment]
> Are there any plans to split o-teaser-collections into something more atomic?

o-teaser-collection now has a primary mixin which enables consumers to include parts of o-teaser-collection independently.

When the front-page redesign rolls out to all readers, we’ll also be able to delete parts of o-teaser-collection 🎉
