### ISSUE TITLE
Demo tweak / oTeaserCollectionAssassination deprecation?

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-teaser-collection#21]
Our `oTeaserCollectionAssassination` demo is looking a little funky. The mixin doesn't appear to be used at a glance outside the demo, so can it be deprecated?

<img width="618" alt="screen shot 2018-01-03 at 10 18 59" src="https://user-images.githubusercontent.com/10405691/34516674-b4a05106-f06f-11e7-88c6-bb65117c55aa.png">

**Comment by gvonkoss** [comment]
As discussed, the assassination is used in special occasions so it won't always be in use. And also as discussed, we'll both be looking at this in the grand scheme of things later on 👍 .
