### ISSUE TITLE
Close up padding top on o-teaser-collection__heading

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-teaser-collection#23]
To better align with the original designs and for the 8px rule to feel connected to the heading and thus give it a clear position in the typographic hierarchy. 

Close up padding top on o-teaser-collection__heading from 20px to **12px**.

This will also allow us to these this style elsewhere on FT.com. 

Current:
![current example top padding of 20px on heading](https://user-images.githubusercontent.com/11214093/37707117-ddc25f54-2cf9-11e8-8d87-1919156c0199.png)

Proposed(with tighter top padding):
![proposed top padding of 12px on heading](https://user-images.githubusercontent.com/11214093/37707125-e43f4cb6-2cf9-11e8-9bb7-0e2391a8226c.png)

**Comment by notlee** [comment]
Released 👍 https://github.com/Financial-Times/o-teaser-collection/releases/tag/v2.1.2
