### ISSUE TITLE
Firefox <29

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/o-teaser-collection#5]
The homepage has some very broken layout for Firefox <29 which I think was introduced by the o-teaser-collection/o-teaser re-write. This is probably a flex-box problem.

In total, visits from Firefox < 29 represent 0.4% of our traffic for December. If there is a simple fix that will cover most of these browsers then it would be good to add it in.

**Comment by onishiweb** [comment]
This turned out to be an `o-grid` issue, fixed in: https://github.com/Financial-Times/o-grid/pull/146
